### ISSUE TITLE
The vent shell is too big

### ISSUE THREAD

**Issue by jorgecis** [TonyBrobston/yet-another-smart-vent#1]
I notice that for the vent 6x12 you split the bigger parts but not the shell, and is not possible to print it using the Prusa (Not the XL that is not available yet)

Can you split the shell?

**Comment by TonyBrobston** [comment]
Yep, that's the plan. 

I've got a note in the readme and a game plan in my head of how to make it happen, should be available in the next few days as long as testing goes well.

Thanks for your interest, let me know if you have any other questions.

**Comment by TonyBrobston** [comment]
First iteration didn't go so well. Working on a second iteration today.

**Comment by TonyBrobston** [comment]
![PXL_20220819_230039489](https://user-images.githubusercontent.com/4724577/185721298-752c6d5e-d590-4b42-b713-0268ba1c5cd1.jpg)
Couple more iterations done. This is pretty solid; I'm surprised this even works. I'll test print a 2x12 in the next day or two. Assuming that works I'll update the 4x12 and 6x12 and test those.

**Comment by Vader699** [comment]
Awesome.  I was looking into the 4x12 and wondering what you thought would be the best way to split the shell.  

And it's kind of too bad having to print the louvers diagonally so they fit on my bed.  going to have to do them one at a time it seems.

**Comment by TonyBrobston** [comment]
All my vents are 4x10 and 6x10, so until less than a week ago, that's all that existed.

This snap together concept is still sort of blowing my mind. It audibly snaps when going together.

Yeah, there's probably a way to make the louver a two-piece design but I think the cons heavily outweigh the pros. I personally have two magnetic print beds, so I glue stick my spare while my primary is running and do a quick swap and keep the printer going. But, obviously I have to be present to do it 🤷‍♂️.

**Comment by TonyBrobston** [comment]
I'm test printing a 2x12 now.

**Comment by TonyBrobston** [comment]
![PXL_20220822_033447771](https://user-images.githubusercontent.com/4724577/185833461-4222cd6d-bcbf-4c9b-8808-7b66f14ba847.jpg)

The shell is printed. It snaps together. It's a bit flimsy until you put the two screws in. I think once the top is printed and installed it will gain enough rigidity to be viable, but I can only speculate until then. I have two longer louvers and end-caps printing now; then two vent top halves after that.

**Comment by TonyBrobston** [comment]
I'm not loving this snap together design.

I'm probably going to iterate on having the vent shell side overlap; the width is 2mm, so I'll print two 1mm walls that overlap. I'll design for four M3 screws to clamp them together. I think this will give more rigidity.

My fear is putting out something that may have issues down the road; it seems like less work to get it right from the start then to apologize for a failing design and try to remedy it later.

**Comment by TonyBrobston** [comment]
I tested this out, works great. Next I'll switch the 4x12 over to this two-piece design.
![2x12-vent1](https://user-images.githubusercontent.com/4724577/186057565-33f7be3b-af89-4906-9f6c-b6d57564f9af.jpg)

**Comment by Vader699** [comment]
Nice looking pretty good!

**Comment by TonyBrobston** [comment]
Thanks!

Slowly but surely and a bit of luck 😄 .

**Comment by TonyBrobston** [comment]
I've got the 4x12 shell printed. Working on the top now, then 2 more louvers. After that I'll know for sure if this works. The split shell is up for 2x12, 4x12, and 6x12; but I've only tested the first.
![PXL_20220824_011418407](https://user-images.githubusercontent.com/4724577/186296065-5641e3bf-fa25-4381-a10e-f601855d307c.jpg)

**Comment by TonyBrobston** [comment]
I tested the 4x12 and it's fantastic. The vent top and specifically the M5 screw give the shell and snap joint way more rigidity than I expected. Essentially the side-to-side flex was bad, but when attaching the top 99% of that goes away. I'll chalk that up to dumb luck.

My printer needs some maintenance, so I won't be testing the 6x12 for awhile.

![PXL_20220824_160235999](https://user-images.githubusercontent.com/4724577/186467287-a8a69e0b-f63f-48e4-b152-56684494d6c7.jpg)
![PXL_20220824_160302001](https://user-images.githubusercontent.com/4724577/186467308-64df0c2b-1d1e-4b1f-9909-417ccb5ee397.jpg)

**Comment by TonyBrobston** [comment]
I'm going to go ahead and close this issue. I'll probably post back once I test the 6x12, but it is going to be awhile. I'm 99% confident it's good to go.

If anyone has any other questions feel free to reopen this issue or open a new issue.
